pipeline {
  agent any

  environment {
    AWS_REGION = "ap-south-1"
    ACCOUNT_ID = "308855860105"
    ECR_REPO = "backend-app"
    IMAGE_TAG = "latest"
  }

  stages {

    stage('Checkout Code') {
      steps {
        git branch: 'main',
        url: 'https://github.com/rahul4793/backend-repo.git'
      }
    }

    stage('Build Docker Image') {
      steps {
sh '''
cd Corporate_Banking_Backend
docker build -t $ECR_REPO:$IMAGE_TAG .
'''      }
    }

    stage('Login to AWS ECR') {
      steps {
        withCredentials([
          [$class: 'AmazonWebServicesCredentialsBinding',
           credentialsId: 'aws-creds']
        ]) {
          sh '''
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          '''
        }
      }
    }

    stage('Push Image to ECR') {
      steps {
        sh '''
        docker tag $ECR_REPO:$IMAGE_TAG \
        $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

        docker push \
        $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
        '''
      }
    }

    stage('Deploy Backend Container') {
      steps {
        sh '''
        docker stop backend || true
        docker rm backend || true

        docker run -d \
        -p 5000:5000 \
        --name backend \
        $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
        '''
      }
    }
  }
}
