spring.application.name=deal-pipeline-backend

# MongoDB (Docker)
spring.data.mongodb.uri=mongodb+srv://rahulgupta:gupta8181@shipmnt.ijxgj.mongodb.net/deal_pipeline
spring.data.mongodb.auto-index-creation=true

# Server
server.port=8080

# JWT
jwt.secret=dealpipeline_secret_123
jwt.expiration=86400000
