spring.application.name=deal-pipeline-backend

# MongoDB (Docker)
spring.data.mongodb.uri=mongodb://mongo:27017/dealpipeline
spring.data.mongodb.auto-index-creation=true

# Server
server.port=8080

# JWT
jwt.secret=dealpipeline_secret_123
jwt.expiration=86400000
