pipeline {
    agent any

    environment {
        AWS_REGION       = "ap-south-1"
        ACCOUNT_ID       = "308855860105"
        ECR_REPO         = "frontend-app"
        IMAGE_TAG        = "latest"
        CONTAINER_NAME   = "frontend"
        HOST_PORT        = "80"
        CONTAINER_PORT   = "80"
    }

    stages {

        stage('Checkout') {
            steps {
                echo "🔹 Checking out code from GitHub..."
                git branch: 'main',
                    url: 'https://github.com/rahul4793/Capstone-Project-Corporate-Banking-Loan-Pricing-Deal-Approval-System.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "🔹 Building Docker image..."
                dir('Corporate_Banking_Frontend') {
                    sh """
                    docker build -t $ECR_REPO:$IMAGE_TAG .
                    """
                }
            }
        }

        stage('Login to ECR') {
            steps {
                echo "🔹 Logging in to ECR..."
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                    sh '''
                    aws ecr get-login-password --region $AWS_REGION \
                    | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                    '''
                }
            }
        }

stage('Push Docker Image to ECR') {
    steps {
        sh """
        docker tag ${ECR_REPO}:${IMAGE_TAG} \
        ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}

        docker push \
        ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
        """
    }
}

stage('Deploy Frontend') {
    steps {
        script {
            echo "🚀 Starting frontend deployment..."

            sh """
            echo "Stopping old container if exists"
            docker ps -a -q -f name=${CONTAINER_NAME} | xargs -r docker stop
            docker ps -a -q -f name=${CONTAINER_NAME} | xargs -r docker rm

            echo "Running new frontend container"
            docker run -d \
              -p ${HOST_PORT}:80 \
              --name ${CONTAINER_NAME} \
              ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
            """
        }
    }
}
    }

    post {
        success {
            echo "🎉 Frontend pipeline completed successfully!"
        }
        failure {
            echo "❌ Frontend pipeline failed. Check the logs above for details."
        }
    }
}
